RADIUS_LEG = 38.1 / 2;

THICKNESS_CLAMP = 5;
HEIGHT_CLAMP_GRIP = 20;
ANGLE_CLAMP_GRIP = 25;

SCREW_TYPE = F1BM3;
SCREW_DIAMETER = SCREW_TYPE[4];

WIDTH_SADDLE = RADIUS_LEG * 1.25;
HEIGHT_SADDLE = insert_hole_length(SCREW_TYPE) + THICKNESS_CLAMP;

DIAMETER_COUNTERSINK_HOLE = 7.5;
HEIGHT_COUNTERSINK_HOLE = get_metric_bolt_head_height(insert_screw_diameter(SCREW_TYPE)) + 3;
DIAMETER_SCREW_HOLE = SCREW_DIAMETER + 0.5;